name: CI Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Copy .env.example to .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install composer dependencies
      run: composer install dependencies
    - name: Generate encryption key
      run: php artisan key:generate
    - name: Set directory permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create temp database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: NPM install
      run: npm install
    - name: PHPCS apply
      run: ./vendor/bin/phpcs
    - name: Execute PHPUnit tests 
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: ./vendor/bin/phpunit
